<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c2e690ef-db07-49f7-9508-568955d01d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;FrontAccounting&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_page_body&quot;] >> internal:role=link[name=&quot;FrontAccounting&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>57ea874f-6334-44d2-a1fa-bf7d3ac0d060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./themes/default/images/logo_frontaccounting.png</value>
      <webElementGuid>e19995e0-0b33-4b95-a160-3baab16c5282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>FrontAccounting</value>
      <webElementGuid>8592f8cb-210d-4af5-af7b-52309208bb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c74ca833-0e1c-4389-ab3e-1eef4cb1f1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>fixPNG(this)</value>
      <webElementGuid>c49d59c9-926f-455e-858a-2cd41bd9d572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f7eee435-f847-4025-ab41-22ff46196d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_page_body&quot;)/form[1]/center[1]/table[@class=&quot;login&quot;]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>41216db8-43e6-4d59-9549-aa8722e0e7dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_page_body']/form/center/table/tbody/tr/td/a/img</value>
      <webElementGuid>e0002281-1250-4ca0-b217-e7ca25b5e58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='FrontAccounting']</value>
      <webElementGuid>868e098d-4072-486e-b360-d25c044c86e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2a228002-3e98-44c5-b011-b9db1de49a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './themes/default/images/logo_frontaccounting.png' and @alt = 'FrontAccounting']</value>
      <webElementGuid>01024e51-be80-4801-8ddf-08be946caf66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
