<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login as user demouser and password p_42366d</name>
   <tag></tag>
   <elementGuidId>f2302535-4530-47c2-b7bc-fb9b76b00cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmitUser']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmitUser&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login -->&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8a42579-5a7d-46ab-ab0a-93b5ce9fc858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>40ec4ca9-4a7f-464c-bfc2-2e85fd9feacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>  Login -->  </value>
      <webElementGuid>3beed692-9331-4218-8b2c-62be8f6aaf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmitUser</value>
      <webElementGuid>e2beb7de-7625-4f53-a930-ba0f66c59ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>set_fullmode();</value>
      <webElementGuid>c11a35b2-3e2c-4222-ba7b-aba8068bcc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_page_body&quot;)/form[1]/center[2]/input[1]</value>
      <webElementGuid>a3a899c6-921d-4c3a-9bdb-4c9355ef7efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmitUser']</value>
      <webElementGuid>fa53657a-4443-4f91-a3da-9cc7a3581f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_page_body']/form/center[2]/input</value>
      <webElementGuid>73bddc08-fb68-4da6-9fc9-aabd3d2ef224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center[2]/input</value>
      <webElementGuid>37b4505e-6643-43a0-aa18-e899aa295579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'SubmitUser']</value>
      <webElementGuid>b29ab3a2-691d-494a-889c-bc103f56e1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
