<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login as user demouser and password p_42366d</name>
   <tag></tag>
   <elementGuidId>f2302535-4530-47c2-b7bc-fb9b76b00cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmitUser']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmitUser&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login -->&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>843b43ac-4f9f-4430-b690-fd70ce73f39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2e835d0e-7bdf-49f2-a46b-a0635e7c7849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>  Login -->  </value>
      <webElementGuid>b0839485-ea24-4d51-a5f0-d19a9e63aea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmitUser</value>
      <webElementGuid>953857e7-3d9c-4c42-ad03-67b097d14b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>set_fullmode();</value>
      <webElementGuid>4b3ea2d8-01b3-4cde-9f36-a8e2dcce6f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_page_body&quot;)/form[1]/center[2]/input[1]</value>
      <webElementGuid>a4f77b4f-ccfc-4299-a3ac-902fcde84dc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmitUser']</value>
      <webElementGuid>abd87276-fa1a-42f7-b035-4af8460d3cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_page_body']/form/center[2]/input</value>
      <webElementGuid>df86ab1c-b227-48c7-8dc5-8089d9e415d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center[2]/input</value>
      <webElementGuid>a623e928-b8ea-4751-a67c-c29f1d5f9501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'SubmitUser']</value>
      <webElementGuid>a960cc9a-450f-4a25-9036-2ea167337bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
